### ISSUE TITLE
Project ownership

### ISSUE THREAD

**Issue by DarrellMozingo** [Pereingo/statsd-csharp-client#64]
@goncalopereira started this project then I took it over, but I've recently moved jobs so I'm not longer using it at all. Don't really feel comfortable making changes for a client I don't personally use, so I'd rather find someone else to take ownership. Takers? @pekiZG I know you've been pretty active on issues/PR's, would you be interested? Still happy to chime in on design or code reviews, just don't want to be the one making the calls :)

**Comment by goncalopereira** [comment]
+1 I'm afraid when we started this there was no statsd client but now I haven't used .net in years.

**Comment by pekiZG** [comment]
I can always hop in and help, but I don't consider myself 'senior' enough to be making the decisions.

I know the project was forked to datadogs, haven't looked what's the difference.
https://github.com/DataDog/dogstatsd-csharp-client

**Comment by DarrellMozingo** [comment]
DataDog's fork is for their commercial product.

I'd be willing to lend a hand. Are you actively using it on projects? I think that's the important bit. There's not a whole lot going on with the project usually so it's a good one to get started with.

**Comment by pekiZG** [comment]
I'm using it on personal and company projects.
Helping/Guiding hand is always appreciated.

**Comment by TerribleDev** [comment]
Hi,

I believe we (various development groups at vistaprint) will ultimately come to either fork this repo, and continue the work. Or constantly submit PR's. Personally, I dislike straight up forks.

We are interested in...

* Supporting dotnet core
* Moving to a more DI centric model (less global configuration, more injecting config classes around)
* Squeeze out as much perf as possible
* Continue to unit test
* Event emitter hooks before and after metrics are sent
* Removal of [artifacts](https://github.com/Pereingo/statsd-csharp-client/tree/master/src/StatsdClient/packages) from the repository
* Separate packages to instrument HttpClient
* Separate package to instrument Model Binding
* Decoupling this project into an interface package, and a client package.
* dotnet cli plugins to allow creating/sending metrics from the cli without netcat

How open are you to continuing to move forward with this project?

**Comment by DarrellMozingo** [comment]
Hi @TerribleDev,

Nice ideas. I really like the HttpClient & MVC instrumentation suggestions. 

Can I ask about the DI centric, separate package for the interface, and the dotnet cli version ideas? What issues are you facing that you're thinking of these routes?

I'd like to avoid forks as well. I'm more than happy to accept PR's and we can move towards commit access and eventually ownership if that looks like a good route?

**Comment by TerribleDev** [comment]
Sure,

Right now configuration is stored as a static, and access to the methods are all static (well they are not in Istatsd, but the docs imply using Metric the static class).

Using statics makes it very hard for people to mock out the objects, and data. This makes testing, less optimal. 

Ideally I'd like to do have an api like the following

```csharp
IStatsdClient statsClient = Metric.Configure(...);

statsClient.Counter("mystat.yo"); 
etc.

```

This allows for 2 things...

1. the ability to have multiple configurations (by the virtue that the configuration is stored in the instant and not in the static)
2. The ability to mock out the data
3. The continued ability to set the configurations elsewhere in the application

We could still do this in a backward compatible manor, but slowly deprecate the old pattern.

Also having the statsclient inherit from an interface (such as IStatsdClient) that is in another package, would let library authors instrument other functions if an optional IStatsdClient is passed. 

dotnet core has moved toward a builtin DI model, so having instances allows users to register their clients in a shared DI container. 

One common thing I have been doing a lot recently is making metrics and using netcat to push them to statsd forwarders for testing purposes. The dotnet cli intergration would be nice so I could just type in a shell `dotnet statsd Counter mystat.yo statsdforwarder.local`

**Comment by pekiZG** [comment]
Would so like to work on this <3

**Comment by DarrellMozingo** [comment]
Have you had the need to assert on what metrics you're sending before? We started with interfaces for this purpose but found we never needed it, so ended up with the simpler static interface in the end.

Can you explain the use case for multiple configurations?

Similar for the separate interface package (for eg `IStatsdClient`) - would it be for a different statsd client? If it's for a different back-end storage, you can already plug those into statsd (such as OpenTSDB, Influx, etc).

Not sure a custom cli tool for sending stats vs the very standard `echo "mystat.yo:1|c" | nc -w 1 -u statsdforwarder.local 8125` is worth it? I suppose it saves having to remember the statsd format string, port, etc though :thinking: If it isn't a big thing to build/publish once it's running on dotnet core I can see this, but I think it wouldn't take much hassle to make it not worth the effort.

Sorry if it comes across as not wanting to change the client - that's not the situation! Just genuinely curious about your use cases for these situations as we've never ran across them before :) I generally take a "no by default" stance on features to keep app bloat down, but am happy to be convinced to include them. Always easier to add than remove!

Anyway, back to the ownership question! If you're happy to open issues for these separate topics we can chat about them and start getting PR's in. I'll be happy to merge in as needed, eventually giving commit access @TerribleDev.

@pekiZG - perhaps you can pick up any issues that interest you and get some experience doing code reviews/issue discussion/etc along the way as well? If @TerribleDev ends up with ownership you can help him out and workout an agreement later.

**Comment by pekiZG** [comment]
@DarrellMozingo  Of course 👍 
always willing to help :)
I'm also worried about changing things if someone or something is depending on me.
That's why I asked for mentoring (to lead is a big responsibility \o/)

**Comment by TerribleDev** [comment]
Hey so...

In short. Obviously I had seriously different and ultimately api breaking changes I needed for this repo. Instead of trying (and ultimately breaking this api and its customers) to make huge changes to this project for my own selfish goals. I decided to make my [own StastD client](https://github.com/TryStatsN/StatsN).

That client is inspired by the work done in this project, but ultimately has a fairly different codebase underlying it. 

Ok now for the flip side. I am very interested in continuing to see projects such as this go on for .net So....I'm not abandoning this project! I'm going to hit up some issues soon and start throwing PR's down. I can't see why both things cannot exist.

To answer some older questions people had/have.


>Can you explain the use case for multiple configurations? 

I work at vistaprint, and some of our code dates back to 2001. We have an legacy monolithic application. That application composes of hundreds of projects, and many teams own code in it. Each team has microservices outside the monolith as well. The monolith couldn't use this client because this client stores configurations as a static, and we have teams that have their own statsd clients. Thus we couldn't use this.

**Comment by DarrellMozingo** [comment]
Fair enough, and thanks very much for the PR Tommy. Much appreciated!

re multiple configs: so each team owns part of a monolith and sends to a different server? I can see needing the separate configs then, though I could suggest using a single bigger instance w/separate metric namespaces, then you can still easily graph across them (though I guess you can do that w/grafana or something anyway).

**Comment by DarrellMozingo** [comment]
For anyone else that stumbles across this and is interested, all open issues/PRs are fixed and I cleaned up the docs/contributing guidelines a bit.

**Comment by bronumski** [comment]
@DarrellMozingo & @TerribleDev,

I know this thread is about product ownership but I wanted to discus further some of the suggestions made above in terms of project direction, specifically restructuring to support interfaces for the purposes of DI.

I can appreciate the want to consider injecting the Metrics client via DI for the purposes of testing. It would be similar to injecting a Logger for the purposes of logging. This is something I would have done in the past. However consider that logging of any sort is cross cutting. If we start injecting loggers and metrics client our already busy constructors would get even busier and the intent of our classes would get lost. Yes we could use property injection but this brings its own noise. Having statically typed clients allows us to dispatch metrics without polluting the class signature. You could take this one step further and use AOP or Event Dispatching that could remove most metric orientated code from the business logic.

Obviously this does not address the situation of how you would test when using the statically typed accessors. This could be addressed in a couple of ways, firstly the static configuration could allow for an alternative component to be configured allowing you to stick in a mocked object. Alternatively if you are doing outside in testing which I do more of now instead of unit testing it is very easy to spin up a UDP listener and validate that the correct message was received. 

I am not suggesting that the API doesn't support interfaces for the metric client, something akin to Log4Net as this would be useful. However I would suggest that the API still supports sending metrics from a static method.

Just my two cents.

**Comment by DarrellMozingo** [comment]
Technically there is the [`IStatsd`](https://github.com/Pereingo/statsd-csharp-client/blob/master/src/StatsdClient/IStatsd.cs) interface you can inject in. It just doesn't have some of the convience of the static `Metrics` class.

**Comment by bronumski** [comment]
@DarrellMozingo - I don't know if you saw the comment I did on the Closed Threading Issue last night. You said to reopen it when I could give an example. I wasn't sure if you wanted me to create a new issue or to comment on that one so that it could be reopened. Sorry for the delay in getting back.

**Comment by DarrellMozingo** [comment]
Project deprecated. See the readme.
